name: hello-world

on: push

job:
  hello-world-job:
  
    runs-on: ubuntu-latest

    steps:
      - name: check out repo code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      
